name: CI Pipeline

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-project/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --legacy-peer-deps

  job2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-project/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --legacy-peer-deps
      - run: npm run build
